bool escapeCondition
bool escapeLockout
bool avoidLockout
bool inSearchableRegion
bool roiTimeExpired
bool possessingSample
bool possibleSample
bool definiteSample
bool sampleInCollectPosition
bool confirmedPossession
bool atHome
bool inDepositPosition
uint32 samplesCollected
uint32 avoidCount
uint32 examineCount
uint32 backupCount
uint32 confirmCollectFailedCount
bool roiKeyframed
uint32 numProcs
bool[] procsToExecute
bool[] procsToInterrupt
bool[] procsBeingExecuted
bool missionEnded
bool setProcState
int32 setProcStateIndex
int32 setProcStateValue
---
