#ifndef CHESTNUT_RIDGE_ROIS_H
#define CHESTNUT_RIDGE_ROIS_H

ROI.e = 123.0 - satMapStartE;
ROI.s = 29.0 - satMapStartS;
ROI.sampleProb = 1.0;
ROI.sampleSig = 10.0;
ROI.radialAxis = 7.5;
ROI.tangentialAxis = 7.5;
ROI.allocatedTime = 180.0;
ROI.highRisk = 0;
ROI.hardLockout = false;
ROI.roiGroup = 0;
ROI.whiteProb = 1.0;
ROI.silverProb = 1.0;
ROI.blueOrPurpleProb = 1.0;
ROI.pinkProb = 1.0;
ROI.redProb = 1.0;
ROI.orangeProb = 1.0;
ROI.yellowProb = 1.0;
regionsOfInterest.push_back(ROI);
ROI.e = 141.0 - satMapStartE;
ROI.s = 48.0 - satMapStartS;
ROI.sampleProb = 0.2;
ROI.sampleSig = 0.5;
ROI.radialAxis = 7.5;
ROI.tangentialAxis = 7.5;
ROI.allocatedTime = 180.0;
ROI.highRisk = 0;
ROI.hardLockout = false;
ROI.roiGroup = 0;
ROI.whiteProb = 1.0;
ROI.silverProb = 1.0;
ROI.blueOrPurpleProb = 1.0;
ROI.pinkProb = 1.0;
ROI.redProb = 1.0;
ROI.orangeProb = 1.0;
ROI.yellowProb = 1.0;
regionsOfInterest.push_back(ROI);
ROI.e = 114.0 - satMapStartE;
ROI.s = 60.0 - satMapStartS;
ROI.sampleProb = 0.2;
ROI.sampleSig = 0.5;
ROI.radialAxis = 7.5;
ROI.tangentialAxis = 7.5;
ROI.allocatedTime = 180.0;
ROI.highRisk = 0;
ROI.hardLockout = false;
ROI.roiGroup = 0;
ROI.whiteProb = 1.0;
ROI.silverProb = 1.0;
ROI.blueOrPurpleProb = 1.0;
ROI.pinkProb = 1.0;
ROI.redProb = 1.0;
ROI.orangeProb = 1.0;
ROI.yellowProb = 1.0;
regionsOfInterest.push_back(ROI);
ROI.e = 140.0 - satMapStartE;
ROI.s = 98.0 - satMapStartS;
ROI.sampleProb = 0.2;
ROI.sampleSig = 0.5;
ROI.radialAxis = 7.5;
ROI.tangentialAxis = 7.5;
ROI.allocatedTime = 180.0;
ROI.highRisk = 0;
ROI.hardLockout = false;
ROI.roiGroup = 0;
ROI.whiteProb = 1.0;
ROI.silverProb = 1.0;
ROI.blueOrPurpleProb = 1.0;
ROI.pinkProb = 1.0;
ROI.redProb = 1.0;
ROI.orangeProb = 1.0;
ROI.yellowProb = 1.0;
regionsOfInterest.push_back(ROI);
ROI.e = 37.5 - satMapStartE;
ROI.s = 28.2 - satMapStartS;
ROI.sampleProb = 0.5;
ROI.sampleSig = 1.0;
ROI.radialAxis = 7.5;
ROI.tangentialAxis = 7.5;
ROI.allocatedTime = 180.0;
ROI.highRisk = 0;
ROI.hardLockout = false;
ROI.roiGroup = 0;
ROI.whiteProb = 1.0;
ROI.silverProb = 1.0;
ROI.blueOrPurpleProb = 1.0;
ROI.pinkProb = 1.0;
ROI.redProb = 1.0;
ROI.orangeProb = 1.0;
ROI.yellowProb = 1.0;
regionsOfInterest.push_back(ROI);
northTransformROIs();

#endif // CHESTNUT_RIDGE_ROIS_H
