#ifndef CHESTNUT_RIDGE_ROIS_H
#define CHESTNUT_RIDGE_ROIS_H

ROI.eMap = 114.8;
ROI.sMap = 34.7;
ROI.sampleProb = 1.0;
ROI.sampleSig = 10.0;
ROI.radialAxis = 7.5;
ROI.tangentialAxis = 7.5;
ROI.allocatedTime = 180.0;
ROI.highRisk = 0;
ROI.hardLockout = false;
ROI.roiGroup = 0;
ROI.whiteProb = 1.0;
ROI.silverProb = 1.0;
ROI.blueOrPurpleProb = 1.0;
ROI.pinkProb = 1.0;
ROI.redProb = 1.0;
ROI.orangeProb = 1.0;
ROI.yellowProb = 1.0;
regionsOfInterest.push_back(ROI);
ROI.eMap = 141.0;
ROI.sMap = 48.0;
ROI.sampleProb = 0.2;
ROI.sampleSig = 0.5;
ROI.radialAxis = 7.5;
ROI.tangentialAxis = 7.5;
ROI.allocatedTime = 180.0;
ROI.highRisk = 0;
ROI.hardLockout = false;
ROI.roiGroup = 0;
ROI.whiteProb = 1.0;
ROI.silverProb = 1.0;
ROI.blueOrPurpleProb = 1.0;
ROI.pinkProb = 1.0;
ROI.redProb = 1.0;
ROI.orangeProb = 1.0;
ROI.yellowProb = 1.0;
regionsOfInterest.push_back(ROI);
ROI.eMap = 114.0;
ROI.sMap = 60.0;
ROI.sampleProb = 0.2;
ROI.sampleSig = 0.5;
ROI.radialAxis = 7.5;
ROI.tangentialAxis = 7.5;
ROI.allocatedTime = 180.0;
ROI.highRisk = 0;
ROI.hardLockout = false;
ROI.roiGroup = 0;
ROI.whiteProb = 1.0;
ROI.silverProb = 1.0;
ROI.blueOrPurpleProb = 1.0;
ROI.pinkProb = 1.0;
ROI.redProb = 1.0;
ROI.orangeProb = 1.0;
ROI.yellowProb = 1.0;
regionsOfInterest.push_back(ROI);
ROI.eMap = 140.0;
ROI.sMap = 98.0;
ROI.sampleProb = 0.2;
ROI.sampleSig = 0.5;
ROI.radialAxis = 7.5;
ROI.tangentialAxis = 7.5;
ROI.allocatedTime = 180.0;
ROI.highRisk = 0;
ROI.hardLockout = false;
ROI.roiGroup = 0;
ROI.whiteProb = 1.0;
ROI.silverProb = 1.0;
ROI.blueOrPurpleProb = 1.0;
ROI.pinkProb = 1.0;
ROI.redProb = 1.0;
ROI.orangeProb = 1.0;
ROI.yellowProb = 1.0;
regionsOfInterest.push_back(ROI);
ROI.eMap = 37.5;
ROI.sMap = 28.2;
ROI.sampleProb = 0.5;
ROI.sampleSig = 1.0;
ROI.radialAxis = 7.5;
ROI.tangentialAxis = 7.5;
ROI.allocatedTime = 180.0;
ROI.highRisk = 0;
ROI.hardLockout = false;
ROI.roiGroup = 0;
ROI.whiteProb = 1.0;
ROI.silverProb = 1.0;
ROI.blueOrPurpleProb = 1.0;
ROI.pinkProb = 1.0;
ROI.redProb = 1.0;
ROI.orangeProb = 1.0;
ROI.yellowProb = 1.0;
regionsOfInterest.push_back(ROI);
northTransformROIs();

#endif // CHESTNUT_RIDGE_ROIS_H
