#ifndef EVANSDALE_FULL_ROIS_H
#define EVANSDALE_FULL_ROIS_H

ROI.e = 171.5 - satMapStartE;
ROI.s = 152.4 - satMapStartS;
ROI.sampleProb = 1.0;
ROI.sampleSig = 1000.0;
ROI.radialAxis = 5.0;
ROI.tangentialAxis = 5.0;
ROI.allocatedTime = 180.0;
ROI.highRisk = 0;
ROI.hardLockout = false;
ROI.roiGroup = 0;
regionsOfInterest.push_back(ROI);
ROI.e = 27.5 - satMapStartE;
ROI.s = 60.7 - satMapStartS;
ROI.sampleProb = 0.2;
ROI.sampleSig = 0.5;
ROI.radialAxis = 5.0;
ROI.tangentialAxis = 5.0;
ROI.allocatedTime = 180.0;
ROI.highRisk = 0;
ROI.hardLockout = false;
ROI.roiGroup = 0;
regionsOfInterest.push_back(ROI);
ROI.e = 36.4 - satMapStartE;
ROI.s = 46.4 - satMapStartS;
ROI.sampleProb = 0.2;
ROI.sampleSig = 0.5;
ROI.radialAxis = 5.0;
ROI.tangentialAxis = 5.0;
ROI.allocatedTime = 180.0;
ROI.highRisk = 0;
ROI.hardLockout = false;
ROI.roiGroup = 0;
regionsOfInterest.push_back(ROI);
ROI.e = 136.5 - satMapStartE;
ROI.s = 116.2 - satMapStartS;
ROI.sampleProb = 0.5;
ROI.sampleSig = 1.0;
ROI.radialAxis = 5.0;
ROI.tangentialAxis = 5.0;
ROI.allocatedTime = 180.0;
ROI.highRisk = 0;
ROI.hardLockout = false;
ROI.roiGroup = 0;
regionsOfInterest.push_back(ROI);
ROI.e = 82.5 - satMapStartE;
ROI.s = 89.8 - satMapStartS;
ROI.sampleProb = 0.2;
ROI.sampleSig = 0.5;
ROI.radialAxis = 5.0;
ROI.tangentialAxis = 5.0;
ROI.allocatedTime = 180.0;
ROI.highRisk = 0;
ROI.hardLockout = false;
ROI.roiGroup = 0;
regionsOfInterest.push_back(ROI);
ROI.e = 111.6 - satMapStartE;
ROI.s = 72.7 - satMapStartS;
ROI.sampleProb = 0.5;
ROI.sampleSig = 1.0;
ROI.radialAxis = 5.0;
ROI.tangentialAxis = 5.0;
ROI.allocatedTime = 180.0;
ROI.highRisk = 0;
ROI.hardLockout = false;
ROI.roiGroup = 0;
regionsOfInterest.push_back(ROI);
ROI.e = 136.7 - satMapStartE;
ROI.s = 145.3 - satMapStartS;
ROI.sampleProb = 0.5;
ROI.sampleSig = 1.0;
ROI.radialAxis = 5.0;
ROI.tangentialAxis = 5.0;
ROI.allocatedTime = 180.0;
ROI.highRisk = 0;
ROI.hardLockout = false;
ROI.roiGroup = 0;
regionsOfInterest.push_back(ROI);
ROI.e = 196.9 - satMapStartE;
ROI.s = 147.6 - satMapStartS;
ROI.sampleProb = 0.5;
ROI.sampleSig = 1.0;
ROI.radialAxis = 5.0;
ROI.tangentialAxis = 5.0;
ROI.allocatedTime = 180.0;
ROI.highRisk = 0;
ROI.hardLockout = false;
ROI.roiGroup = 0;
regionsOfInterest.push_back(ROI);
ROI.e = 197.1 - satMapStartE;
ROI.s = 126.4 - satMapStartS;
ROI.sampleProb = 0.5;
ROI.sampleSig = 1.0;
ROI.radialAxis = 5.0;
ROI.tangentialAxis = 5.0;
ROI.allocatedTime = 180.0;
ROI.highRisk = 0;
ROI.hardLockout = false;
ROI.roiGroup = 0;
regionsOfInterest.push_back(ROI);
ROI.e = 233.3 - satMapStartE;
ROI.s = 148.0 - satMapStartS;
ROI.sampleProb = 0.5;
ROI.sampleSig = 1.0;
ROI.radialAxis = 5.0;
ROI.tangentialAxis = 5.0;
ROI.allocatedTime = 180.0;
ROI.highRisk = 0;
ROI.hardLockout = false;
ROI.roiGroup = 0;
regionsOfInterest.push_back(ROI);
northTransformROIs();

#endif // EVANSDALE_FULL_ROIS_H
