#ifndef EVANSDALE_FULL_ROIS_H
#define EVANSDALE_FULL_ROIS_H

ROI.e = 259.3 - satMapStartE;
ROI.s = 201.0 - satMapStartS;
ROI.sampleProb = 1.0;
ROI.sampleSig = 10.0;
ROI.radialAxis = 5.0;
ROI.tangentialAxis = 5.0;
ROI.searched = false;
regionsOfInterest.push_back(ROI);
ROI.e = 120.0 - satMapStartE;
ROI.s = 113.7 - satMapStartS;
ROI.sampleProb = 5.0;
ROI.sampleSig = 1.0;
ROI.radialAxis = 5.0;
ROI.tangentialAxis = 5.0;
ROI.searched = false;
regionsOfInterest.push_back(ROI);
ROI.e = 130.0 - satMapStartE;
ROI.s = 97.3 - satMapStartS;
ROI.sampleProb = 5.0;
ROI.sampleSig = 1.0;
ROI.radialAxis = 5.0;
ROI.tangentialAxis = 5.0;
ROI.searched = false;
regionsOfInterest.push_back(ROI);
ROI.e = 146.3 - satMapStartE;
ROI.s = 117.3 - satMapStartS;
ROI.sampleProb = 5.0;
ROI.sampleSig = 1.0;
ROI.radialAxis = 5.0;
ROI.tangentialAxis = 5.0;
ROI.searched = false;
regionsOfInterest.push_back(ROI);
ROI.e = 172.0 - satMapStartE;
ROI.s = 137.0 - satMapStartS;
ROI.sampleProb = 5.0;
ROI.sampleSig = 1.0;
ROI.radialAxis = 5.0;
ROI.tangentialAxis = 5.0;
ROI.searched = false;
regionsOfInterest.push_back(ROI);
ROI.e = 200.0 - satMapStartE;
ROI.s = 116.7 - satMapStartS;
ROI.sampleProb = 5.0;
ROI.sampleSig = 1.0;
ROI.radialAxis = 5.0;
ROI.tangentialAxis = 5.0;
ROI.searched = false;
regionsOfInterest.push_back(ROI);
ROI.e = 228.7 - satMapStartE;
ROI.s = 199.3 - satMapStartS;
ROI.sampleProb = 5.0;
ROI.sampleSig = 1.0;
ROI.radialAxis = 5.0;
ROI.tangentialAxis = 5.0;
ROI.searched = false;
regionsOfInterest.push_back(ROI);
ROI.e = 289.7 - satMapStartE;
ROI.s = 199.0 - satMapStartS;
ROI.sampleProb = 5.0;
ROI.sampleSig = 1.0;
ROI.radialAxis = 5.0;
ROI.tangentialAxis = 5.0;
ROI.searched = false;
regionsOfInterest.push_back(ROI);
ROI.e = 289.3 - satMapStartE;
ROI.s = 177.0 - satMapStartS;
ROI.sampleProb = 5.0;
ROI.sampleSig = 1.0;
ROI.radialAxis = 5.0;
ROI.tangentialAxis = 5.0;
ROI.searched = false;
regionsOfInterest.push_back(ROI);
ROI.e = 323.7 - satMapStartE;
ROI.s = 198.7 - satMapStartS;
ROI.sampleProb = 5.0;
ROI.sampleSig = 1.0;
ROI.radialAxis = 5.0;
ROI.tangentialAxis = 5.0;
ROI.searched = false;
regionsOfInterest.push_back(ROI);
northTransformROIs();

#endif // EVANSDALE_FULL_ROIS_H
