uint32 modROIIndex
bool setHardLockoutROI
bool hardLockoutROIState
bool setPosES
float32 e
float32 s
bool setPosXY
float32 x
float32 y
bool setROISize
float32 radialAxis
float32 tangentialAxis
bool setSampleProps
float32 sampleProb
float32 sampleSig
float32 whiteProb
float32 silverProb
float32 blueOrPurpleProb
float32 pinkProb
float32 redProb
float32 orangeProb
float32 yellowProb
bool addNewROI
bool newROIInESNotXY
ROI newROI
bool deleteROI
uint32 numDeleteROI
bool editGroup
---
